### ISSUE TITLE
[coc.nvim] Error on notification "formatSelected": formatRange provider not found for current buffer, your language server doesn't support it.

### ISSUE THREAD

**Issue by gou4shi1** [yaegassy/coc-sqlfluff#12]
with latest coc

**Comment by yaegassy** [comment]
`coc-sqlfluff` does not support the ability to format by range. This is because the `sqlfluff` cli tool itself does not have an option to specify a range. <https://docs.sqlfluff.com/en/stable/cli.html#sqlfluff-fix>

**Comment by gou4shi1** [comment]
Maybe we can send selected file content to the `sqlfluff`?
