### ISSUE TITLE
can this work in parallel with coc-sql

### ISSUE THREAD

**Issue by laoshaw** [yaegassy/coc-sqlfluff#14]
or they are in conflict somehow?

**Comment by yaegassy** [comment]
`coc-sqlfluff` is an coc-extension for SQLFluff, a Python linter and formatter. `coc-sql` is an coc-extension using sql-formatter and node-sql-parser from js/ts.

For linting feature, coc-sqlfluff and coc-sql can be used at the same time, but only one of the formatter feature is used.

sqlfluff is a quirky tool and may be slow; if sqlfluff is not needed, it may be better to use coc-sql only.
