### ISSUE TITLE
Is this compatible with Vim?

### ISSUE THREAD

**Issue by jjjchens235** [yaegassy/coc-sqlfluff#5]
I'm trying to find a Vim plugin for sqlfluff. Does the one you created require Nvim + coc? I'm not too familiar with those, so I apologize in advance if this is a dumb question.

**Comment by yaegassy** [comment]
A simple explanation of coc.nvim is that it is a "VSCode-like" plugin for Vim8/Neovim. `coc-sqlfluff` is an extension (like an extra plugin) for `coc.nvim`. 

`coc.nvim` has `.nvim` in the plugin name, but it also works with `Vim8`.

**Comment by jjjchens235** [comment]
Got it thanks. I will download coc.nvim then and go from there.
